import { createFileRoute, Link } from "@tanstack/react-router";
import { BedDouble, CalendarDays, ChevronRight, CircleDollarSign, House, LayoutDashboard, Mail, Menu, MessageSquare, TrendingUp, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { property, formatCurrency } from "@/lib/property";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [
  { title: `Owner Dashboard — ${property.name}` }, { name: "description", content: `Sample owner workspace for managing ${property.name}.` }, { property: "og:title", content: `Owner Dashboard — ${property.name}` }, { property: "og:description", content: "Reservations, guests, availability, and property management." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: AdminPage });
const nav = [[LayoutDashboard,"Overview"],[CalendarDays,"Reservations"],[Users,"Guests"],[BedDouble,"Availability"],[CircleDollarSign,"Pricing"],[House,"Property information"],[MessageSquare,"Guest messages"]] as const;
function AdminPage() { return <div className="min-h-screen bg-muted"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-border bg-footer p-6 text-footer-foreground lg:block"><Link to="/" className="font-display text-2xl">{property.name}</Link><p className="mt-1 text-xs text-footer-muted">Owner workspace</p><nav className="mt-10 grid gap-1">{nav.map(([Icon,label],i) => <button key={label} className={`flex items-center gap-3 px-3 py-3 text-left text-sm ${i===0 ? "bg-primary text-primary-foreground" : "text-footer-muted hover:text-footer-foreground"}`}><Icon className="size-4"/>{label}</button>)}</nav></aside>
  <main className="lg:ml-64"><header className="flex h-20 items-center justify-between border-b border-border bg-background px-5 md:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden"><Menu/></Button><div><p className="text-xs text-muted-foreground">Thursday, September 17</p><h1 className="text-xl font-semibold">Good afternoon, Jay</h1></div></div><div className="flex items-center gap-3"><Button variant="ghost" size="icon"><Mail/></Button><div className="grid size-10 place-items-center rounded-full bg-primary text-sm font-bold text-primary-foreground">JT</div></div></header>
  <div className="p-5 md:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Overview</p><h2 className="mt-2 font-display text-4xl">Your property at a glance</h2></div><Button>+ Add reservation</Button></div>
  <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Upcoming stays","12","Next 30 days"],["Occupancy","78%","+6% this month"],["Revenue",formatCurrency(14280),"September"],["Unread messages","5","2 need replies"]].map(([a,b,c]) => <article key={a} className="border border-border bg-background p-5"><p className="text-sm text-muted-foreground">{a}</p><p className="mt-3 font-display text-4xl">{b}</p><p className="mt-2 flex items-center gap-1 text-xs text-primary"><TrendingUp className="size-3"/>{c}</p></article>)}</div>
  <div className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="border border-border bg-background"><div className="flex items-center justify-between border-b border-border p-5"><h3 className="font-semibold">Upcoming reservations</h3><button className="text-sm text-primary">View all</button></div><div className="divide-y divide-border">{[["Sofia Lim","Sep 20–25","5 nights","Confirmed"],["Noah Williams","Sep 28–Oct 2","4 nights","Confirmed"],["Mia Chen","Oct 5–10","5 nights","Pending"]].map(r => <div key={r[0]} className="grid grid-cols-[1fr_auto] gap-2 p-5 sm:grid-cols-[1.2fr_1fr_.7fr_auto]"><div className="font-semibold">{r[0]}</div><div className="text-sm text-muted-foreground">{r[1]}</div><div className="hidden text-sm text-muted-foreground sm:block">{r[2]}</div><span className="text-xs font-semibold text-primary">{r[3]}</span></div>)}</div></section><section className="border border-border bg-background p-5"><h3 className="font-semibold">Quick actions</h3><div className="mt-4 divide-y divide-border">{nav.slice(3).map(([Icon,label]) => <button key={label} className="flex w-full items-center justify-between py-4 text-sm"><span className="flex items-center gap-3"><Icon className="size-4 text-primary"/>{label}</span><ChevronRight className="size-4 text-muted-foreground"/></button>)}</div></section></div></div></main></div> }