import { createFileRoute } from "@tanstack/react-router";
import { differenceInCalendarDays } from "date-fns";
import { CalendarCheck, Check, Minus, Plus, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { formatCurrency, heroPhoto, property } from "@/lib/property";

type BookingSearch = { checkIn?: string; checkOut?: string; guests?: number };
export const Route = createFileRoute("/booking")({ validateSearch: (search: Record<string, unknown>): BookingSearch => {
 const parsed: BookingSearch = {};
 if (typeof search["checkIn"] === "string") parsed.checkIn = search["checkIn"];
 if (typeof search["checkOut"] === "string") parsed.checkOut = search["checkOut"];
 const guests = Number(search["guests"]);
 if (Number.isFinite(guests) && guests > 0) parsed.guests = guests;
 return parsed;
}, head: () => ({ meta: [
 { title: `Book Your Stay — ${property.name}` }, { name: "description", content: `Check sample availability and plan your direct stay at ${property.name} in Siargao.` }, { property: "og:title", content: `Book ${property.name}` }, { property: "og:description", content: "Choose your dates, review transparent pricing, and request your stay." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: BookingPage });

function BookingPage(){ const search=Route.useSearch(); const [checkIn,setCheckIn]=useState(search["checkIn"]??""); const [checkOut,setCheckOut]=useState(search["checkOut"]??""); const [guests,setGuests]=useState(search["guests"]??2); const [confirmed,setConfirmed]=useState(false);
 const nights=useMemo(()=>{if(!checkIn||!checkOut)return 0; return Math.max(0,differenceInCalendarDays(new Date(`${checkOut}T12:00:00`),new Date(`${checkIn}T12:00:00`)))},[checkIn,checkOut]); const subtotal=nights*property.nightlyRate; const service=Math.round(subtotal*property.serviceRate); const total=subtotal+(nights?property.cleaningFee:0)+service; const available=nights>0;
 if(confirmed)return <><SiteHeader/><main className="grid min-h-[72vh] place-items-center px-4 py-20"><div className="max-w-lg text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-primary text-primary-foreground"><Check/></span><p className="eyebrow mt-8">Request received</p><h1 className="mt-3 font-display text-5xl">Your island stay is one step closer.</h1><p className="mt-5 leading-7 text-muted-foreground">This sample confirmation shows how a completed booking will feel. No payment was taken and no reservation was saved.</p><Button className="mt-8" onClick={()=>setConfirmed(false)}>Back to booking</Button></div></main><SiteFooter/></>;
 return <><SiteHeader/><main><section className="bg-secondary py-14"><div className="site-container"><p className="eyebrow">Direct booking</p><h1 className="mt-3 font-display text-5xl sm:text-6xl">Plan your stay.</h1><p className="mt-4 max-w-xl text-muted-foreground">Choose your dates, review the complete price, and send your booking request.</p></div></section><section className="section-pad"><form onSubmit={e=>{e.preventDefault();setConfirmed(true)}} className="site-container grid gap-10 lg:grid-cols-[1fr_24rem]"><div><h2 className="font-display text-3xl">1. Dates & guests</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Check-in</span><input className="field" type="date" value={checkIn} onChange={e=>setCheckIn(e.target.value)} required/></label><label><span className="mb-2 block text-sm font-semibold">Check-out</span><input className="field" type="date" min={checkIn} value={checkOut} onChange={e=>setCheckOut(e.target.value)} required/></label></div><div className="mt-5 flex items-center justify-between border border-border p-4"><div><p className="text-sm font-semibold">Guests</p><p className="text-xs text-muted-foreground">Maximum {property.capacity} guests</p></div><div className="flex items-center gap-4"><Button type="button" variant="secondary" size="icon" aria-label="Remove guest" onClick={()=>setGuests(Math.max(1,guests-1))}><Minus className="size-4"/></Button><span className="w-5 text-center font-semibold">{guests}</span><Button type="button" variant="secondary" size="icon" aria-label="Add guest" onClick={()=>setGuests(Math.min(property.capacity,guests+1))}><Plus className="size-4"/></Button></div></div>{checkIn&&checkOut&&<div className={`mt-5 flex items-center gap-3 border p-4 ${available?"border-primary bg-secondary":"border-destructive"}`}><CalendarCheck className="size-5"/><p className="text-sm font-semibold">{available?`Available for ${nights} ${nights===1?"night":"nights"}`:"Choose a checkout date after check-in"}</p></div>}
 <div className="mt-12 border-t border-border pt-10"><h2 className="font-display text-3xl">2. Guest information</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">First name</span><input className="field" required/></label><label><span className="mb-2 block text-sm font-semibold">Last name</span><input className="field" required/></label><label><span className="mb-2 block text-sm font-semibold">Email</span><input className="field" type="email" required/></label><label><span className="mb-2 block text-sm font-semibold">Phone</span><input className="field" type="tel" required/></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">Anything we should know? <span className="font-normal text-muted-foreground">(optional)</span></span><textarea className="field min-h-28" placeholder="Arrival time, special occasion, or questions"/></label></div></div></div>
 <aside><div className="sticky top-6 border border-border bg-background p-5 shadow-elevated"><img src={heroPhoto.src} alt={heroPhoto.alt} width={1920} height={1200} className="aspect-[16/9] w-full object-cover"/><p className="mt-4 text-sm font-semibold">{property.name}</p><p className="text-xs text-muted-foreground">{property.shortLocation} · {property.rating} ★</p><div className="my-5 border-t border-border"/><div className="flex justify-between text-sm"><span>{formatCurrency(property.nightlyRate)} × {nights} nights</span><span>{formatCurrency(subtotal)}</span></div><div className="mt-3 flex justify-between text-sm"><span>Cleaning fee</span><span>{formatCurrency(nights?property.cleaningFee:0)}</span></div><div className="mt-3 flex justify-between text-sm"><span>Service fee</span><span>{formatCurrency(service)}</span></div><div className="my-5 border-t border-border"/><div className="flex justify-between font-semibold"><span>Total</span><span>{formatCurrency(total)}</span></div><Button type="submit" className="mt-6 w-full" size="lg" disabled={!available}>Request to book</Button><p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-muted-foreground"><ShieldCheck className="size-4"/>You won't be charged in this demo</p></div></aside></form></section></main><SiteFooter/></> }