import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, BookOpen } from "lucide-react";
import { PageIntro, SiteFooter, SiteHeader } from "@/components/site-chrome";
import { guideSections, property } from "@/lib/property";

export const Route = createFileRoute("/guide")({ head: () => ({ meta: [
  { title: `Guest Guide — ${property.name}` }, { name: "description", content: `Arrival, house information, local recommendations, and checkout details for guests of ${property.name}.` },
  { property: "og:title", content: `Guest Guide — ${property.name}` }, { property: "og:description", content: "Everything you need for a smooth, relaxed stay." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: GuidePage });

function GuidePage() { return <><SiteHeader /><main><section className="section-pad bg-secondary"><div className="site-container"><PageIntro eyebrow="Your stay, made simple" title="The guest guide" description="Practical information for a smooth stay. Private access details are shared only with confirmed guests." /></div></section>
  <section className="section-pad"><div className="site-container grid gap-12 lg:grid-cols-[16rem_1fr]"><aside><div className="sticky top-8 border-l border-border pl-5"><p className="eyebrow mb-4">In this guide</p>{guideSections.map(s => <a key={s.id} href={`#${s.id}`} className="block py-2 text-sm text-muted-foreground hover:text-foreground">{s.title}</a>)}</div></aside><div className="grid gap-4">{guideSections.map((s, i) => <article id={s.id} key={s.id} className="scroll-mt-8 border-b border-border py-8 first:pt-0"><div className="flex items-start gap-5"><span className="font-display text-3xl text-muted-foreground">{String(i+1).padStart(2,"0")}</span><div><p className="eyebrow">{s.eyebrow}</p><h2 className="mt-2 font-display text-4xl">{s.title}</h2><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">{s.text}</p>{s.id === "emergency" && <a href={`mailto:${property.email}`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Contact the host <ArrowUpRight className="size-4" /></a>}</div></div></article>)}</div></div></section>
  <section className="bg-primary py-16 text-primary-foreground"><div className="site-container flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center"><div><BookOpen className="mb-4 size-6"/><h2 className="font-display text-4xl">Still have a question?</h2><p className="mt-2 opacity-80">Your local host is only a message away.</p></div><a href={`mailto:${property.email}`} className="border border-primary-foreground px-6 py-3 text-sm font-semibold">Email the host</a></div></section></main><SiteFooter /></> }