import { createFileRoute, Link } from "@tanstack/react-router";
import * as Dialog from "@radix-ui/react-dialog";
import { AirVent, ArrowRight, BedDouble, Car, ChefHat, ChevronRight, Clock, MapPin, Maximize2, ShieldCheck, Star, Tv, Users, Waves, Wifi, X } from "lucide-react";
import { useState } from "react";
import { BookingSearch } from "@/components/booking-search";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { Button } from "@/components/ui/button";
import { amenities, highlights, images, nearby, property, reviews, rules } from "@/lib/property";

export const Route = createFileRoute("/")({ head: () => ({ meta: [
  { title: `${property.name} — Luxury Villa in Siargao` }, { name: "description", content: "Book a private, design-led tropical villa in Siargao directly. Four bedrooms, infinity pool, and thoughtful local hosting." }, { property: "og:title", content: `${property.name} — Siargao` }, { property: "og:description", content: property.tagline }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: HomePage });

const amenityIcons = [Wifi, AirVent, ChefHat, Tv, Waves, Car, ShieldCheck];
function SectionHead({ eyebrow, title, side }: { eyebrow: string; title: string; side?: string }) { return <div className="mb-10 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 max-w-2xl font-display text-4xl leading-tight sm:text-5xl">{title}</h2></div>{side && <p className="max-w-sm text-sm leading-6 text-muted-foreground">{side}</p>}</div> }

function HomePage() {
 const [openImage, setOpenImage] = useState<number | null>(null);
 return <><main><section className="relative min-h-[760px] overflow-hidden text-hero-foreground"><img src={images[0].src} alt={images[0].alt} width={1920} height={1200} className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-linear-to-b from-foreground/45 via-foreground/5 to-foreground/60"/><SiteHeader overlay/><div className="site-container relative z-10 flex min-h-[660px] items-end pb-24"><div className="max-w-3xl"><p className="mb-5 flex items-center gap-2 text-sm font-semibold"><MapPin className="size-4"/>{property.location}</p><h1 className="font-display text-6xl leading-[.9] sm:text-7xl lg:text-8xl">{property.name}</h1><p className="mt-5 max-w-xl text-base leading-7 sm:text-lg">{property.tagline}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild variant="hero" size="lg"><Link to="/booking">Book your stay</Link></Button><Button asChild variant="heroOutline" size="lg"><a href="#property">Explore property</a></Button></div></div></div></section>
 <div className="site-container relative z-20 -mt-16"><BookingSearch/></div>
 <section className="pt-20 pb-12"><div className="site-container"><div className="grid grid-cols-2 border-y border-border md:grid-cols-5">{highlights.map(([label,value],i)=><div key={label} className={`py-6 text-center ${i>0 ? "border-l border-border" : ""}`}><p className="font-display text-2xl sm:text-3xl">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div></div></section>
 <section id="property" className="section-pad"><div className="site-container"><SectionHead eyebrow="Considered comfort" title="Everything you need. Nothing you don't." side="Private spaces, modern essentials, and attentive support for a stay that feels effortless."/><div className="grid grid-cols-2 gap-px border border-border bg-border md:grid-cols-4">{amenities.map((a,i)=>{const Icon=amenityIcons[i]; return <div key={a} className="bg-background p-6 sm:p-8"><Icon className="size-5 text-primary"/><p className="mt-5 text-sm font-semibold">{a}</p></div>})}<Link to="/guide" className="flex items-center justify-between bg-primary p-6 text-sm font-semibold text-primary-foreground sm:p-8">View all amenities<ArrowRight className="size-4"/></Link></div></div></section>
 <section className="section-pad bg-secondary"><div className="site-container"><SectionHead eyebrow="A closer look" title="Made for living beautifully." side="Open each photograph to explore the details."/><div className="grid auto-rows-[15rem] grid-cols-2 gap-3 md:auto-rows-[20rem] md:grid-cols-4">{images.map((image,i)=><button key={image.src} onClick={()=>setOpenImage(i)} className={`group relative overflow-hidden ${i===0 ? "col-span-2 row-span-2" : i===2 ? "row-span-2" : ""}`} aria-label={`Open image: ${image.alt}`}><img src={image.src} alt={image.alt} width={image.width} height={image.height} loading={i===0?undefined:"lazy"} className="size-full object-cover transition-transform duration-700 group-hover:scale-[1.03]"/><span className="absolute right-3 top-3 grid size-9 place-items-center bg-background text-foreground opacity-0 transition-opacity group-hover:opacity-100"><Maximize2 className="size-4"/></span></button>)}</div></div></section>
 <Dialog.Root open={openImage!==null} onOpenChange={(v)=>!v&&setOpenImage(null)}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-footer/95"/><Dialog.Content className="fixed inset-0 z-50 grid place-items-center p-5" aria-describedby={undefined}><Dialog.Title className="sr-only">Property gallery</Dialog.Title>{openImage!==null&&<img src={images[openImage].src} alt={images[openImage].alt} className="max-h-[88vh] max-w-[92vw] object-contain"/>}<Dialog.Close className="absolute right-5 top-5 grid size-11 place-items-center border border-footer-muted text-footer-foreground" aria-label="Close gallery"><X/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
 <section className="section-pad"><div className="site-container grid items-center gap-12 lg:grid-cols-2"><img src={images[1].src} alt={images[1].alt} width={1408} height={1056} loading="lazy" className="aspect-[4/5] size-full object-cover lg:aspect-[4/3]"/><div className="lg:pl-12"><p className="eyebrow">About the property</p><h2 className="mt-4 font-display text-5xl leading-tight">Island ease, elevated.</h2><p className="mt-6 leading-8 text-muted-foreground">{property.description}</p><p className="mt-4 leading-8 text-muted-foreground">Each bedroom is a private retreat, while generous shared spaces make gathering feel natural. Daily housekeeping and a local host keep the practical details quietly taken care of.</p><Button asChild variant="secondary" className="mt-8"><Link to="/guide">Discover the guest experience <ArrowRight className="size-4"/></Link></Button></div></div></section>
 <section className="section-pad bg-secondary"><div className="site-container"><SectionHead eyebrow="The neighborhood" title="Close to the island's best, quietly set apart."/><div className="grid gap-5 lg:grid-cols-[1.25fr_1fr]"><div className="relative min-h-[430px] overflow-hidden bg-muted"><div className="absolute inset-0 opacity-50 [background-image:linear-gradient(var(--color-border)_1px,transparent_1px),linear-gradient(90deg,var(--color-border)_1px,transparent_1px)] [background-size:48px_48px]"/><div className="absolute left-[20%] top-[28%] h-px w-[55%] rotate-12 bg-primary/50"/><div className="absolute left-[35%] top-[55%] h-px w-[45%] -rotate-20 bg-primary/50"/><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-primary text-primary-foreground shadow-elevated"><MapPin/></span><p className="mt-3 bg-background px-3 py-2 text-sm font-semibold">{property.name}</p></div></div><div className="border-y border-border">{nearby.map(item=><div key={item.name} className="flex items-center justify-between border-b border-border py-5 last:border-0"><div><p className="eyebrow">{item.category}</p><p className="mt-1 font-semibold">{item.name}</p></div><span className="flex items-center gap-2 text-sm text-muted-foreground"><Clock className="size-4"/>{item.time}</span></div>)}</div></div></div></section>
 <section className="section-pad"><div className="site-container"><SectionHead eyebrow="Your stay" title="Thoughtful from arrival to farewell."/><div className="grid gap-10 md:grid-cols-3">{[["01","Before","A local host shares your arrival guide, access details, and personalized recommendations."],["02","During","Daily housekeeping and responsive support, with complete privacy whenever you prefer."],["03","After","A simple checkout and a direct line to us whenever the island calls you back."]].map(x=><article key={x[0]} className="border-t border-border pt-6"><span className="font-display text-3xl text-primary">{x[0]}</span><h3 className="mt-8 font-display text-3xl">{x[1]}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{x[2]}</p></article>)}</div></div></section>
 <section className="section-pad bg-primary text-primary-foreground"><div className="site-container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2"><Star className="size-5 fill-current"/><span className="text-2xl font-semibold">{property.rating}</span><span className="opacity-70">· {property.reviewCount} guest reviews</span></div><h2 className="mt-5 font-display text-5xl">Loved by our guests.</h2></div></div><div className="mt-12 grid gap-8 md:grid-cols-3">{reviews.map(r=><blockquote key={r.name} className="border-t border-primary-foreground/30 pt-6"><p className="font-display text-2xl leading-8">“{r.quote}”</p><footer className="mt-8"><p className="text-sm font-semibold">{r.name}</p><p className="mt-1 text-xs opacity-65">{r.stay}</p></footer></blockquote>)}</div></div></section>
 <section className="section-pad"><div className="site-container"><SectionHead eyebrow="Good to know" title="House rules, simply stated."/><div className="grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{rules.map(([title,text])=><div key={title} className="bg-background p-7"><p className="text-xs text-muted-foreground">{title}</p><p className="mt-3 font-display text-2xl">{text}</p></div>)}</div></div></section>
 <section className="relative overflow-hidden py-28 text-center text-hero-foreground"><img src={images[3].src} alt="" width={1408} height={1008} loading="lazy" className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-foreground/55"/><div className="site-container relative"><p className="eyebrow text-hero-foreground">Your island escape</p><h2 className="mt-4 font-display text-6xl">Ready for your stay?</h2><p className="mx-auto mt-4 max-w-md">Book directly for attentive hosting and the best available rate.</p><Button asChild variant="hero" size="lg" className="mt-8"><Link to="/booking">Book your stay <ChevronRight className="size-4"/></Link></Button></div></section>
 </main><SiteFooter/></>;
}