import { createFileRoute, Link } from "@tanstack/react-router";
import * as Dialog from "@radix-ui/react-dialog";
import { AirVent, ArrowRight, Bath, BedDouble, BriefcaseBusiness, Building2, ChefHat, ChevronRight, MapPin, Maximize2, Monitor, Sofa, Sparkles, Star, TrainFront, Tv, Users, Waves, Wifi, X } from "lucide-react";
import { useState } from "react";
import { BookingSearch } from "@/components/booking-search";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { Button } from "@/components/ui/button";
import { amenities, heroPhoto, highlights, images, kitchenettePhoto, nearby, property } from "@/lib/property";

export const Route = createFileRoute("/")({ head: () => ({ meta: [
  { title: "Cozy Minimalist Studio in Cubao | Direct Booking" },
  { name: "description", content: "A cozy minimalist studio for up to four guests near Gateway Mall, MRT and LRT in Cubao, Quezon City." },
  { property: "og:title", content: property.fullName },
  { property: "og:description", content: "A comfortable, thoughtfully designed condo in the heart of Cubao." },
  { property: "og:type", content: "website" },
  { name: "twitter:card", content: "summary_large_image" },
] }), component: HomePage });

const amenityIcons = [Wifi, AirVent, ChefHat, Tv, BriefcaseBusiness, Bath, Waves, Building2];
const infoIcons = [Users, BedDouble, Sofa, Bath, MapPin];
const stayReasons = [
  { Icon: TrainFront, title: "Easy to get around", text: "Near MRT, LRT, and major Cubao destinations." },
  { Icon: Sofa, title: "Made for comfort", text: "A cozy minimalist setup with practical essentials." },
  { Icon: BriefcaseBusiness, title: "Flexible city stays", text: "Well suited to study trips, work visits, and staycations." },
  { Icon: Building2, title: "Everything nearby", text: "Malls, cafés, restaurants, and transport are close by." },
];

function SectionHead({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) {
  return <div className="mb-8 max-w-2xl"><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 font-display text-4xl leading-tight sm:text-5xl">{title}</h2>{text && <p className="mt-4 text-sm leading-7 text-muted-foreground sm:text-base">{text}</p>}</div>;
}

function HomePage() {
  const [openImage, setOpenImage] = useState<number | null>(null);
  return <><SiteHeader /><main>
    <section className="hero-grid site-container grid items-center gap-8 py-9 md:min-h-[620px] md:grid-cols-[.92fr_1.08fr] md:gap-10 md:py-14 lg:min-h-[680px]">
      <div className="max-w-xl py-2 md:py-4"><p className="eyebrow flex items-center gap-2"><MapPin className="size-4" />Cubao, Quezon City</p><h1 className="mt-5 font-display text-4xl leading-[1.05] sm:text-6xl">Your cozy stay in the heart of Cubao</h1><p className="mt-5 text-base leading-7 text-muted-foreground">A thoughtfully designed minimalist condo for staycations, study trips, work visits, and easy city getaways near Gateway and MRT.</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/booking">Book your stay <ArrowRight className="size-4" /></Link></Button><Button asChild variant="secondary" size="lg"><a href="#space">Explore the space</a></Button></div><p className="mt-5 text-xs text-muted-foreground">Entire rental unit · Aurora Escalades Tower</p></div>
      <button onClick={() => setOpenImage(0)} className="group relative min-h-[380px] overflow-hidden md:h-[560px]" aria-label="Open studio photo"><img src={heroPhoto.src} alt={heroPhoto.alt} width={heroPhoto.width} height={heroPhoto.height} className="absolute inset-0 size-full object-cover transition-transform duration-700 group-hover:scale-[1.025]" /><span className="absolute bottom-4 right-4 flex items-center gap-2 bg-background px-4 py-2 text-xs font-semibold text-foreground"><Maximize2 className="size-4" />View photo</span></button>
    </section>

    <section aria-label="Property details" className="border-y border-border bg-secondary/55"><div className="site-container grid grid-cols-2 md:grid-cols-5">{highlights.map(([label, value], i) => { const Icon = infoIcons[i] ?? MapPin; return <div key={label} className="flex items-center gap-3 border-border px-3 py-5 md:border-r md:last:border-r-0"><Icon className="size-4 shrink-0 text-primary" /><div><p className="text-sm font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></div>; })}</div></section>

    <section id="space" className="section-pad scroll-mt-16"><div className="site-container grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><img src={kitchenettePhoto.src} alt={kitchenettePhoto.alt} width={kitchenettePhoto.width} height={kitchenettePhoto.height} loading="lazy" className="aspect-[4/3] size-full object-cover object-center" /><div className="lg:pl-8"><SectionHead eyebrow="The space" title="Simple, warm, and made for easy stays." text={property.description} /><div className="grid grid-cols-2 gap-x-6 gap-y-4 border-t border-border pt-6 text-sm">{["Comfortable sleeping area", "Sofa bed", "Air conditioning", "Kitchenette", "Private bathroom", "Dedicated workspace", "TV", "Wi-Fi"].map(item => <div key={item} className="flex items-center gap-2"><Sparkles className="size-3.5 text-primary" />{item}</div>)}</div></div></div></section>

    <section className="section-pad bg-secondary/55"><div className="site-container"><SectionHead eyebrow="Inside the studio" title="A closer look" text="Real photographs from the property, from the main living space to the kitchenette and shared pool." /><div className="grid auto-rows-[185px] grid-cols-2 gap-2 sm:auto-rows-[240px] md:grid-cols-4">{images.slice(0, 7).map((image, i) => <button key={image.src} onClick={() => setOpenImage(i)} className={`group relative overflow-hidden ${i === 0 ? "col-span-2 row-span-2" : i === 1 ? "row-span-2" : ""}`} aria-label={`Open image: ${image.alt}`}><img src={image.src} alt={image.alt} width={image.width} height={image.height} loading={i === 0 ? undefined : "lazy"} className="size-full object-cover transition-transform duration-700 group-hover:scale-[1.035]" /><span className="absolute right-3 top-3 grid size-9 place-items-center bg-background text-foreground opacity-0 transition-opacity group-hover:opacity-100"><Maximize2 className="size-4" /></span></button>)}</div></div></section>

    <Dialog.Root open={openImage !== null} onOpenChange={(value) => !value && setOpenImage(null)}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-footer/95" /><Dialog.Content className="fixed inset-0 z-50 grid place-items-center p-5" aria-describedby={undefined}><Dialog.Title className="sr-only">Studio gallery</Dialog.Title>{openImage !== null && images[openImage] ? <img src={images[openImage].src} alt={images[openImage].alt} className="max-h-[90vh] max-w-[92vw] object-contain" /> : null}<Dialog.Close className="absolute right-5 top-5 grid size-11 place-items-center border border-footer-muted text-footer-foreground" aria-label="Close gallery"><X /></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>

    <section id="amenities" className="section-pad scroll-mt-16"><div className="site-container"><SectionHead eyebrow="What you'll have" title="The essentials, thoughtfully covered." /><div className="grid grid-cols-2 border-l border-t border-border sm:grid-cols-4">{amenities.map((item, i) => { const Icon = amenityIcons[i] ?? Wifi; return <div key={item} className="border-b border-r border-border p-5 sm:p-6"><Icon className="size-5 text-primary" /><p className="mt-4 text-sm font-medium">{item}</p></div>; })}</div><Button asChild variant="secondary" className="mt-6"><Link to="/guide">View guest guide <ArrowRight className="size-4" /></Link></Button></div></section>

    <section id="location" className="section-pad scroll-mt-16 bg-accent/45"><div className="site-container grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><SectionHead eyebrow="Cubao, Quezon City" title="Stay in the heart of Cubao" text="Well placed for shopping, dining, study, work, and getting around Metro Manila. The exact address is shared only with confirmed guests." /><div className="space-y-1">{nearby.map(item => <div key={item.name} className="flex items-center justify-between border-b border-border py-3.5"><span className="text-sm font-medium">{item.name}</span><span className="text-xs text-muted-foreground">{item.category}</span></div>)}</div></div><div className="relative min-h-[380px] overflow-hidden bg-muted"><div className="absolute inset-0 opacity-60 [background-image:linear-gradient(var(--color-border)_1px,transparent_1px),linear-gradient(90deg,var(--color-border)_1px,transparent_1px)] [background-size:44px_44px]" /><div className="absolute left-[15%] top-[38%] h-px w-[72%] rotate-12 bg-primary/35" /><div className="absolute left-[28%] top-[64%] h-px w-[58%] -rotate-20 bg-primary/35" /><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-primary text-primary-foreground shadow-soft"><MapPin className="size-5" /></span><p className="mt-3 bg-background px-4 py-2 text-sm font-semibold">Cubao, Quezon City</p></div></div></div></section>

    <section className="section-pad"><div className="site-container"><SectionHead eyebrow="Why stay here" title="Comfort and convenience, in balance." /><div className="grid gap-7 md:grid-cols-4">{stayReasons.map(({ Icon, title, text }) => <article key={title} className="border-t border-border pt-5"><Icon className="size-5 text-primary" /><h3 className="mt-5 font-display text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>

    <section className="bg-primary py-14 text-primary-foreground"><div className="site-container grid gap-8 md:grid-cols-[.72fr_1.28fr] md:items-center"><div><p className="text-sm font-semibold uppercase">Direct booking</p><h2 className="mt-3 font-display text-4xl">Plan your Cubao stay.</h2><p className="mt-3 max-w-md text-sm leading-6 opacity-80">Choose your dates and guests. Live availability will be connected in a future update.</p></div><BookingSearch compact /></div></section>

    <section className="section-pad"><div className="site-container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHead eyebrow="Guest guide" title="Everything you need for a smooth stay" text="Confirmed guests will receive private access details, while practical stay information remains easy to find here." /><Button asChild variant="secondary"><Link to="/guide">Open guest guide <ChevronRight className="size-4" /></Link></Button></div><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4">{["Check-in instructions","Wi-Fi","Parking","Building amenities","House rules","Checkout instructions","Key return","Nearby places"].map(item => <Link key={item} to="/guide" className="bg-secondary p-4 text-sm font-medium transition-colors hover:bg-accent">{item}</Link>)}</div></div></section>

    <section className="border-y border-border bg-secondary/55 py-16"><div className="site-container grid gap-8 md:grid-cols-[.65fr_1.35fr] md:items-center"><div><div className="flex items-center gap-2"><Star className="size-5 fill-current text-primary" /><span className="text-2xl font-semibold">{property.rating}</span><span className="text-sm text-muted-foreground">/ 5</span></div><p className="mt-2 text-sm text-muted-foreground">{property.reviewCount} public Airbnb reviews</p></div><div><p className="eyebrow">Guest feedback</p><h2 className="mt-3 font-display text-4xl">A guest favorite in Cubao.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">Guests highlight the smooth check-in experience and the calm, convenient location. Review excerpts are not reproduced here without verified text.</p></div></div></section>

    <section className="py-20"><div className="site-container text-center"><p className="eyebrow">Your next city stay</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-5xl">Make yourself at home in Cubao</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-muted-foreground">Whether you're visiting for a quick getaway, studying, working, or exploring the city, enjoy a comfortable stay in the heart of Cubao.</p><Button asChild size="lg" className="mt-7"><Link to="/booking">Book your stay <ArrowRight className="size-4" /></Link></Button></div></section>
  </main><SiteFooter /></>;
}